### PR TITLE
Fix download progress bug

### LINKED ISSUE #715: Request from targets of task type download never call completion block
Requests of the task type download never call the completion block when executed. This behaviour can be seen in the demo project. Tapping the download button will show a progress bar but the bar will never disappear when the request finishes. The expected result would be that the progress bar turns green on success and disappears when the request has finished.

The reason why this happens is that the `DownloadRequest` type does not inherit from the `DataRequest` type. In the function `sendAlamofireRequest` in `Moya+Internal.swift`, [the current request is cast to `DataRequest` which then handles the callbacks](https://github.com/Moya/Moya/blob/master/Source/Moya%2BInternal.swift#L220-L231). Since `DownloadRequest` does not inherit from `DataRequest` the cast always fails for those the download type and the proper callback logic never gets called.

### PR DESCRIPTION
**Pull request by petester42**
Closes #715

As detailed in #715, the callbacks of the download requests were never being called because the `DownloadRequest` does not inherit from the `DataRequest`.

What was changed was that there is now an different cast for download requests. This is based on the [code that is found in the Alamofire example] (https://github.com/Alamofire/Alamofire/blob/master/Example/Source/DetailViewController.swift#L104-L112). The second casts fixes the completion block never getting called issue but the progress is still wrong.

I noticed when trying to write tests for this that the progress object will never have its completed property be true since it requires a response to be present. In all the code for progress tracking a response is never set so what I did is that on request completion update the progress object to have a response. Doing so has the desired effect of having the progress object returning completed.

This also contributes to increasing the code coverage from #668.

### CODE REVIEW

File: Source/Moya+Internal.swift [hunk 1]
```diff
@@ -228,6 +228,18 @@ private extension MoyaProvider {
...
+                let result = convertResponseToResult(handler.response, request: handler.request, data: nil, error: handler.error)
+                // Inform all plugins about the response
+                plugins.forEach { $0.didReceiveResponse(result, target: target) }
+                progressCompletion?(ProgressResponse(response: result.value))
+                completion(result)
+            })
+            
+            if let dataRequest = dataRequest as? T {
+                progressAlamoRequest = dataRequest
+            }
```
Comment (ashfurrow) [inline Source/Moya+Internal.swift]: Looks like this `else if` block looks very similar to the one above it, it's just the `progressCompletion` block that's called here and not above. Do you think there's a better abstraction we could use to avoid the repetition?

**Comment by ashfurrow** [comment]
Great PR, thanks! The only feedback I have is in the comment above. If you like, we can address it now, or we can open an issue to address it later.

File: Source/Moya+Internal.swift (hunk 1 above)
Comment (ashfurrow) [inline Source/Moya+Internal.swift]: For example, we could create a protocol with the required methods from both `DataRequest` and `Download Request`, and then extend those types to conform to that protocol. Then our conditional `if let` could cast to the protocol. What do you think?

Comment (petester42) [inline Source/Moya+Internal.swift]: I think that would be a good idea. I'll look into it.

**Comment by Ernest-su** [comment]
still not call .completed in RxMoyaProvider.

**Comment by BasThomas** [comment]
@Ernest-su, what do you mean? Is this a possible bug? If you create an issue for that, please do!

**Comment by petester42** [comment]
That's possible. I don't think that scenario has been tested.
