### PR TITLE
Fix a bug that decodable mapping won't decode nested json array

### LINKED ISSUE #1381: The response map to decodable array always failed.
See this line of code from branch 10.0.0-dev:
https://github.com/Moya/Moya/blob/a951eeab47ad7f4ef780b63e085704b576bbc3be/Sources/Moya/Response.swift#L127
If the response data at given key path is an array, the type cast to `Dictionary<String, Any>` will always fail, and the result is throw an error.

### PR DESCRIPTION
**Pull request by devxoul**
Fixes #1381

### CODE REVIEW

File: Sources/Moya/Response.swift [hunk 1]
```diff
@@ -124,11 +124,11 @@ public extension Response {
     func map<D: Decodable>(_ type: D.Type, atKeyPath keyPath: String? = nil, using decoder: JSONDecoder = JSONDecoder()) throws -> D {
         let jsonData: Data
         if let keyPath = keyPath {
-            guard let jsonDictionary = (try mapJSON() as? NSDictionary)?.value(forKeyPath: keyPath) as? [String: Any] else {
+            guard let jsonObject = (try mapJSON() as? NSDictionary)?.value(forKeyPath: keyPath) else {
                 throw MoyaError.jsonMapping(self)
             }
             do {
-                jsonData = try JSONSerialization.data(withJSONObject: jsonDictionary, options: [])
+                jsonData = try JSONSerialization.data(withJSONObject: jsonObject, options: [])
```
Comment (BasThomas) [inline Sources/Moya/Response.swift]: Nit: you can omit the `options` parameter - it has a default value of `[]`.

File: Tests/Observable+MoyaSpec.swift [hunk 2]
```diff
@@ -326,6 +326,23 @@ class ObservableMoyaSpec: QuickSpec {
                 expect(receivedObject?.createdAt) == formatter.date(from: "1995-01-14T12:34:56")!
             }
 
+            it("maps data representing a json array at a key path to a decodable object") {
```
Comment (AndrewSB) [inline Tests/Observable+MoyaSpec.swift]: nit: it would be nice to mark tests we add from bug reports with the bug report that found it. So adding something like bug from Moya/Moya#1311 would be awesome

File: Sources/Moya/Response.swift (hunk 1 above)
Comment (devxoul) [reply Sources/Moya/Response.swift]: Oh didn't know that. It would be great!

File: Tests/Observable+MoyaSpec.swift (hunk 2 above)
Comment (devxoul) [reply Tests/Observable+MoyaSpec.swift]: That's a great idea.

**Comment by sunshinejr** [comment]
@devxoul would you rebase it so we can merge this one in? 😉

**Comment by devxoul** [comment]
@sunshinejr Sure!

**Comment by SD10** [comment]
SD10 Bot Has Commented 😂:

`❌  fatal error: URLEncoding is disallowed as bodyEncoding.: file /Users/distiller/Moya/Sources/Moya/Endpoint.swift, line 95`
