### PR TITLE
Fix progress object with invalid Content-Length headers.

### LINKED ISSUE #1771: RxSwift: requestWithProgress().filterCompleted() no onNext events
Moya version: 11.0.2, but also tested with Moya 12

I am using Moya with RxSwift, using the `requestWithProgress` function to get the response and progress on uploading a file.

The progress part is working perfectly, however, I found that when I used the response, my other Rx operations on the provided Observable weren't working correctly. When I debugged what was going on, I noticed that the Observable I received from doing:

```swift
requestWithProgress(...).filterCompleted()
```

was only firing an `onCompleted` and then dispose. There was no `onNext` that contained the actual response.

To get this working instead of using the provided `filterCompleted` I just had to do it myself with:

```swift
requestWithProgress(...)
  .map { $0.response }
  .filter { $0 != nil }
  .map { $0! }
```

In short, this is pulling out the response field, filtering for when it isn't nil and then unwrapping the optional.

When I use this instead, everything works as expected. I think the `filterCompleted` implementation is firing no `onNext` events. The type `Observable<Response>` and the comment on the function suggest that it should be providing an Observable that gives you the response and then an onCompleted event, so I think there is a bug there.

For now my code is working with what I put above, so its not blocking me from using this, but just raising this issue, as I think there is a bug that may be affecting others.

### PR DESCRIPTION
**Pull request by sunshinejr**
Fixes #1771.

### CODE REVIEW

File: Tests/MoyaProviderSpec.swift [hunk 1]
```diff
@@ -794,7 +796,85 @@ final class MoyaProviderSpec: QuickSpec {
...
+                            error = err
+                        }
+                        done()
+                    }
+
+                    provider.request(target, callbackQueue: nil, progress: progressClosure, completion: progressCompletionClosure)
+                }
+
+                expect(error).to(beNil())
+                expect(progressValues) == [0, 0, 0, 0, 1.0]
```
Comment (LucianoPAlmeida) [inline Tests/MoyaProviderSpec.swift]: This is just curiosity, there is a reason for all moya equal tests use `expect(value) ==` instead of `.to(equal(value))`?

Comment (sunshinejr) [reply Tests/MoyaProviderSpec.swift]: @LucianoPAlmeida I guess I just use it because it's a lot more convenient to just type `==` instead of `.to(equal(value))`.

File: Changelog.md [hunk 2]
```diff
@@ -1,7 +1,12 @@
 # Next
+
+### Changed
 - `MoyaError` now conforms to `CustomNSError` protocol, makes underlying errors available in its user-info dictionary. [#1783](https://github.com/Moya/Moya/pull/1783) by [@dpoggi](https://github.com/dpoggi).
 - **Breaking Change** `.mapImage()` extension on `Single` and `Observable` now returns non-optional image. [#1789](https://github.com/Moya/Moya/pull/1789), [#1799](https://github.com/Moya/Moya/pull/1799) by [@bjarkehs](https://github.com/bjarkehs) and [@sunshinejr](https://github.com/sunshinejr).
 
+### Fixed
+- Fixed `Progress` object on responses that did not specify correct `Content-Length` header. Now, whenever there is no valid header, the progress will be 0.0 until the completion of the request. Also, the `completed` property is now `true` only when the response was serialized, we do not rely on progress being 1.0 anymore. [#1813](https://github.com/Moya/Moya/pull/1783) by [@sunshinejr](https://github.com/sunshinejr).
+
```
Comment (pedrovereza) [inline Changelog.md]: I think the link should be `https://github.com/Moya/Moya/pull/1813`, it's pointing to pr `1783` right now 😄

Comment (pedrovereza) [reply Changelog.md]: Wait, it should actually point to this pr:

```
[#1815](https://github.com/Moya/Moya/pull/1815)
```

Comment (sunshinejr) [reply Changelog.md]: 🤦‍♂️ thanks @pedrovereza!
