### PR TITLE
Fix Alamofire validation not being performed on uploadMultipart

### LINKED ISSUE #1590: ValidationType not working with uploadMultipart
Moya 11.0 using CocoaPods

- The new ValidationType has something with the uploadMultipart, why there is no validation on the multipart upload?
- The below is the debugger output when printing down the **result** from the *requestNormal* function in the **MoyaProvider+Internal.swift**

```lldb
(lldb) po result
▿ .success(Status Code: 400, Data Length: 104)
  ▿ success : Status Code: 400, Data Length: 104
```

### PR DESCRIPTION
**Pull request by SD10**
Resolves #1590 

Alamofire validation was not being performed on `.uploadMultipart` requests. I've added a backing unit test for this.

### CODE REVIEW

File: Tests/TestHelpers.swift [hunk 1]
```diff
@@ -171,6 +181,20 @@ extension GitHubUserContent: TargetType {
     }
 }
 
+// MARK: - Upload Multipart Helpers
+
+extension HTTPBin {
+    static func createMultipartFormData() -> [MultipartFormData] {
+        let url = Bundle(for: MoyaProviderSpec.self).url(forResource: "testImage", withExtension: "png")!
```
Comment (BasThomas) [inline Tests/TestHelpers.swift]: I know it's a helper, but maybe `fatalError` here too?

File: Tests/MoyaProviderIntegrationTests.swift [hunk 2]
```diff
@@ -299,6 +299,30 @@ final class MoyaProviderIntegrationTests: QuickSpec {
...
+                provider.request(target) { result in
+                    switch result {
+                    case .success(let response):
+                        let validCodes = target.validationType.statusCodes
+                        expect(validCodes).to(contain(response.statusCode))
+                    case .failure(let error):
+                        switch error {
+                        case .underlying(_, let response):
+                            let validCodes = target.validationType.statusCodes
+                            expect(validCodes).toNot(contain(response!.statusCode))
```
Comment (BasThomas) [inline Tests/MoyaProviderIntegrationTests.swift]: Can we assume to always have a `response` here?

File: Tests/TestHelpers.swift (hunk 1 above)
Comment (SD10) [reply Tests/TestHelpers.swift]: Sounds like a good idea to me 👍

File: Tests/MoyaProviderIntegrationTests.swift (hunk 2 above)
Comment (SD10) [reply Tests/MoyaProviderIntegrationTests.swift]: I think our hands are tied on this one. Response validation is only done on Alamofire integration tests. So I can't stub and ensure a response 😕 This could be an improvement

File: Sources/Moya/MoyaProvider+Internal.swift [hunk 3]
```diff
@@ -162,7 +162,9 @@ private extension MoyaProvider {
                     self.cancelCompletion(completion, target: target)
                     return
                 }
-                cancellable.innerCancellable = self.sendAlamofireRequest(alamoRequest, target: target, callbackQueue: callbackQueue, progress: progress, completion: completion)
+                let validationCodes = target.validationType.statusCodes
+                let validated = validationCodes.isEmpty ? alamoRequest : alamoRequest.validate(statusCode: validationCodes)
```
Comment (sunshinejr) [inline Sources/Moya/MoyaProvider+Internal.swift]: `validatedRequest`?

File: Tests/MoyaProviderIntegrationTests.swift [hunk 4]
```diff
@@ -299,6 +299,30 @@ final class MoyaProviderIntegrationTests: QuickSpec {
...
             }
         }
+
+        // Resolves ValidationType not working with multipart upload #1590
+        describe("a provider performing a multipart upload with Alamofire validation") {
+            it("only allows status code 287") {
+                let formData = HTTPBin.createMultipartFormData()
+                let target = HTTPBin.validatedUploadMultipart(formData, nil)
+                let provider = MoyaProvider<HTTPBin>()
+                provider.request(target) { result in
```
Comment (sunshinejr) [inline Tests/MoyaProviderIntegrationTests.swift]: I would restructure this testing code a little bit. Instead of using `expect`s inside the closures, we could use `waitUntil` structure. This makes sure we don't skip this test, where with using `expect`s inside the closure we are risking the situation where this test is skipped, e.g. when closure is not executed. See tests above for examples.

File: Sources/Moya/MoyaProvider+Internal.swift (hunk 3 above)
Comment (SD10) [reply Sources/Moya/MoyaProvider+Internal.swift]: Ugh, that is what I had originally. I knew I should've left it 😆

File: Tests/MoyaProviderIntegrationTests.swift (hunk 4 above)
Comment (SD10) [reply Tests/MoyaProviderIntegrationTests.swift]: Great catch. I totally forgot about that

File: Tests/TestHelpers.swift [hunk 5]
```diff
@@ -113,14 +114,23 @@ enum HTTPBin: TargetType {
...
         }
     }
 
     var headers: [String: String]? {
         return nil
     }
+
+    var validationType: ValidationType {
+        switch self {
+        case .validatedUploadMultipart:
```
Comment (sunshinejr) [inline Tests/TestHelpers.swift]: hmm, how about adding `customCodes` as an associated value, so we can provide it in tests? we could also comment in tests _why_ do we use this constant

File: Tests/MoyaProviderIntegrationTests.swift [hunk 6]
```diff
@@ -299,6 +299,30 @@ final class MoyaProviderIntegrationTests: QuickSpec {
                 }
             }
         }
+
+        // Resolves ValidationType not working with multipart upload #1590
+        describe("a provider performing a multipart upload with Alamofire validation") {
+            it("only allows status code 287") {
```
Comment (sunshinejr) [inline Tests/MoyaProviderIntegrationTests.swift]: how about `it returns error for status code different than 287` and then we could add another case `it returns valid response for status code 287`

File: Tests/TestHelpers.swift [hunk 7]
```diff
@@ -171,6 +181,24 @@ extension GitHubUserContent: TargetType {
     }
 }
 
+// MARK: - Upload Multipart Helpers
+
+extension HTTPBin {
+    static func createMultipartFormData() -> [MultipartFormData] {
```
Comment (sunshinejr) [inline Tests/TestHelpers.swift]: nitpick: we could change the name to include test in it, e.g. `createTestMultipartFormData()`

File: Tests/TestHelpers.swift (hunk 5 above)
Comment (SD10) [reply Tests/TestHelpers.swift]: I can do that 👌. To be honest the reason why this is such a hack of a test is I can't validate a stubbed request. Or else I wouldn't need another enum case 😕

File: Tests/MoyaProviderIntegrationTests.swift (hunk 6 above)
Comment (SD10) [reply Tests/MoyaProviderIntegrationTests.swift]: I wasn't able to test for `287` specifically because I have no control over the actual response since this is not a stub. I just tested for `ValidationType.successCodes` instead

File: Tests/MoyaProviderIntegrationTests.swift [hunk 8]
```diff
@@ -299,6 +299,49 @@ final class MoyaProviderIntegrationTests: QuickSpec {
                 }
             }
         }
+
+        // Resolves ValidationType not working with multipart upload #1590
+        describe("a provider performing a multipart upload with Alamofire validation") {
+            let provider = MoyaProvider<HTTPBin>()
+            let formData = HTTPBin.createTestMultipartFormData()
+            it("returns an error for status code different than 287") {
```
Comment (sunshinejr) [inline Tests/MoyaProviderIntegrationTests.swift]: last one, can we add few empty lines to the code? looks really stacked 😅 

e.g. before `it("")`, in `it("")` we could use a 3 blocks scenario similar to Act-Act-Assert which would add new line before `waitUntil` and one before expects.

**Comment by SD10** [comment]
@sunshinejr No problem, I added some spacing between the tests. LMK if this is 👌
