### PR TITLE
Skip building testing libraries for SPM users.

### LINKED ISSUE #1919: Adding Moya as a dependency in Swift Package Manager causes the Previews in Xcode11 to crash.
**Moya version**: 13.0.1

I added the dependency in Swift Package Manager, and i see that the Package.swift for Moya includes in it's targets all the dependencies incluiding _ReactiveMoya_ and _RXMoya_.

The project builds and runs without any problem. But for some reason, loading the previews in Xcode does not work.

I also tried to change my project using Cocoapods instead of SPM, and using pods the previews actually worked.

The actual error message is the next one:

```
linker command failed with exit code 1 (use -v to see invocation)

----------------------------------------

Failed to build the scheme "theMovieUI": Link /Users/user/Library/Developer/Xcode/DerivedData/theMovieUI-fvtkhqlopskkqueykjpedojefpoa/Build/Intermediates.noindex/Previews/theMovieUI/Products/Debug-iphonesimulator/libCwlCatchException.dylib:
Undefined symbols for architecture x86_64:
  "_catchExceptionOfKind", referenced from:
      CwlCatchException.(catchReturnTypeConverter in _841BEC3F94220F0DFD4EA4E9DDB3DC93)<A where A: __C.NSException>(_: A.Type, block: () -> ()) -> A? in CwlCatchException.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)


Link /Users/user/Library/Developer/Xcode/DerivedData/theMovieUI-fvtkhqlopskkqueykjpedojefpoa/Build/Intermediates.noindex/Previews/theMovieUI/Products/Debug-iphonesimulator/libCwlPreconditionTesting.dylib:
clang: error: no such file or directory: '/Users/user/Library/Developer/Xcode/DerivedData/theMovieUI-fvtkhqlopskkqueykjpedojefpoa/Build/Intermediates.noindex/Previews/theMovieUI/Products/Debug-iphonesimulator/libCwlCatchException.dylib'
Command Ld failed with a nonzero exit code
```
I think the error comes from another dependency. But with the built-in SPM in XCode 11 i can't configure my dependencies to be excluded when compiling, because it does not generate a **Package.swift** file.

Maybe there's something I'm doing wrong? Or some configuration that I'm missing?

### PR DESCRIPTION
**Pull request by sunshinejr**
Fixes #1919. ~Needs to wait for https://github.com/ReactiveCocoa/ReactiveSwift/pull/758 as they pull Quick/Nimble as well.~

### CODE REVIEW

File: Package.swift [hunk 1]
```diff
@@ -1,5 +1,62 @@
...
 import PackageDescription
+import class Foundation.ProcessInfo
+
+let shouldTest = ProcessInfo.processInfo.environment["TEST"] == "1"
+
+func resolveDependencies() -> [Package.Dependency] {
+    let baseDependencies: [Package.Dependency] = [
+        .package(url: "https://github.com/Alamofire/Alamofire.git", .exact("5.0.0-rc.2")),
+        .package(url: "https://github.com/sunshinejr/ReactiveSwift.git", .branch("feature/split_spm_testing_deps")),
+        .package(url: "https://github.com/ReactiveX/RxSwift.git", .upToNextMajor(from: "5.0.0")),
```
Comment (MoyaBot) [inline Package.swift]: - :warning: Collection literals should not have trailing commas. (`trailing_comma`)

File: Package.swift [hunk 2]
```diff
@@ -1,5 +1,62 @@
...
+    ]
+
+    if shouldTest {
+        let testDependencies: [Package.Dependency] = [
+            .package(url: "https://github.com/Quick/Quick.git", .upToNextMajor(from: "2.0.0")),
+            .package(url: "https://github.com/Quick/Nimble.git", .upToNextMajor(from: "8.0.0")),
+            .package(url: "https://github.com/AliSoftware/OHHTTPStubs.git", .branch("feature/spm-support")),
```
Comment (MoyaBot) [inline Package.swift]: - :warning: Collection literals should not have trailing commas. (`trailing_comma`)

**Comment by sunshinejr** [comment]
I'm not sure if this PR on ReactiveSwift is gonna pass or not, so [I created our own fork](https://github.com/Moya/ReactiveSwift) in the meantime (in Moya organization). 

Zrzut ekranu 2019-09-27 o 13 03 51

We will use our own fork by default for SPM integration but if anyone would want to use the original version of ReactiveSwift there is no problem as well. Gonna add documentation about that in a second.

File: Package.swift [hunk 3]
```diff
@@ -1,5 +1,62 @@
...
+    } else {
+        return baseDependencies
+    }
+}
+
+func resolveTargets() -> [Target] {
+    let baseTargets: [Target] = [
+        .target(name: "Moya", dependencies: ["Alamofire"]),
+        .target(name: "ReactiveMoya", dependencies: ["Moya", "ReactiveSwift"]),
+        .target(name: "RxMoya", dependencies: ["Moya", "RxSwift"]),
```
Comment (MoyaBot) [inline Package.swift]: - :warning: Collection literals should not have trailing commas. (`trailing_comma`)
