### PR TITLE
Fixes CI

### LINKED ISSUE #665: CI Failing
Since https://github.com/Moya/Moya/pull/661 was merged, CI is failing. This is likely because the CocoaPods podspec for ReactiveSwift the Carthage commit hash we're referencing are different. I'll take a look and see what we can do.

### PR DESCRIPTION
**Pull request by ashfurrow**
Fixes #665. Also excludes the Demo app from our code coverage report.

### CODE REVIEW

**Comment by ashfurrow** [comment]
Trying to split up Carthage validation onto Travis, so they can run in parallel and save build time. We'll see!

File: Demo/Tests/SignalProducer+MoyaSpec.swift [hunk 1]
```diff
@@ -258,14 +246,12 @@ class SignalProducerMoyaSpec: QuickSpec {
...
-                signal.mapString().start { (event) -> Void in
-                    switch event {
-                    case .next:
+                signal.mapString().startWithResult { result -> Void in
+                    switch result {
+                    case .success:
                         fail("next called for invalid data")
-                    case .failed(let error):
+                    case .failure(let error):
                         receivedError = error
```
Comment (ashfurrow) [inline Demo/Tests/SignalProducer+MoyaSpec.swift]: Do these changes make sense to you, @justinmakaila? I don't want to do something non-idiomatic to ReactiveSwift.

**Comment by ashfurrow** [comment]
Nah, never mind. Travis is having outages, might be worth reconsidering separately, but not now.

**Comment by ashfurrow** [comment]
Danger failing again, gotta learn not to force-push to PRs...
